<?php
/**
 * BudgetDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ynab
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ynab;

/**
 * BudgetDetailTest Class Doc Comment
 *
 * @category    Class
 * @description BudgetDetail
 * @package     Ynab
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BudgetDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BudgetDetail"
     */
    public function testBudgetDetail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "date_format"
     */
    public function testPropertyDateFormat()
    {
    }

    /**
     * Test attribute "currency_format"
     */
    public function testPropertyCurrencyFormat()
    {
    }

    /**
     * Test attribute "accounts"
     */
    public function testPropertyAccounts()
    {
    }

    /**
     * Test attribute "payees"
     */
    public function testPropertyPayees()
    {
    }

    /**
     * Test attribute "payee_locations"
     */
    public function testPropertyPayeeLocations()
    {
    }

    /**
     * Test attribute "category_groups"
     */
    public function testPropertyCategoryGroups()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "months"
     */
    public function testPropertyMonths()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }

    /**
     * Test attribute "subtransactions"
     */
    public function testPropertySubtransactions()
    {
    }

    /**
     * Test attribute "scheduled_transactions"
     */
    public function testPropertyScheduledTransactions()
    {
    }

    /**
     * Test attribute "scheduled_subtransactions"
     */
    public function testPropertyScheduledSubtransactions()
    {
    }
}
